# Generated by Django 4.0.3 on 2022-03-08 23:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('driver_age', models.IntegerField()),
                ('driver_gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=255)),
                ('driver_employment', models.CharField(choices=[('employed', 'Employed'), ('homemaker', 'Homemaker'), ('other_emp', 'Other'), ('retired', 'Retired'), ('student', 'Student'), ('unemployed', 'Unemployed')], max_length=255)),
                ('driver_marital', models.CharField(choices=[('married', 'Married'), ('single', 'Single')], max_length=255)),
                ('driver_location', models.CharField(choices=[('rural', 'Rural'), ('suburban', 'Suburban'), ('urban', 'Urban')], max_length=255)),
                ('vehicle_age', models.IntegerField()),
                ('vehicle_model', models.CharField(choices=[('coupe_cabriolet', 'Coupe'), ('hatchback', 'Hatchback'), ('other_model', 'Other'), ('pickup', 'Pickup'), ('sedan', 'Sedan'), ('suv', 'Suv'), ('van', 'Van')], max_length=255)),
                ('insurance_premium', models.FloatField()),
                ('insurance_claims', models.IntegerField()),
                ('insurance_losses', models.FloatField()),
            ],
        ),
    ]
